Add tela manutenção mecânico
radialserial/FleetFix pull request #21
Opened 2024-12-10 20:42 UTC by rezende009debora

2024-12-10 20:56 UTC, rezende009debora reviewed
É essa a tela

2024-12-10 21:23 UTC, radialserial requested changes

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/lista_historico.xml
Esse arquivo deveria ser chamado `item_historico.xml` para seguir a convenção dos outros arquivos.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_menu_manutencao_m.xml
Pode deletar esse arquivo, menu será feito de outra forma.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_historico_servico_m.xml
> +    <TextView
Remover esse `TextView`, o título da tela será mostrado de outra forma.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/drawable/ic_manutencao.png
[fragment_menu_manutencao_m.xml](https://github.com/radialserial/FleetFix/pull/21/files#diff-c8c4fa02be2183a1e00991ba4ec78d5c446f0f4a8f458d988797fd140871c597) não é necessário, pode deletar esse ícone.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/drawable/card_background.xml
[fragment_menu_manutencao_m.xml](https://github.com/radialserial/FleetFix/pull/21/files#diff-c8c4fa02be2183a1e00991ba4ec78d5c446f0f4a8f458d988797fd140871c597) não é necessário, pode deletar esse recurso.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/ManutencaoM.kt
Os menus serão feitos de outra forma, pode deletar esse arquivo.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/HistoricoServicoM.kt
Esse arquivo deve ser chamado de `FragmentHistoricoServico`.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_historico_servico_m.xml
Esse arquivo deve ser chamado `fragment_historico_servico.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_historico_servico_m.xml
> +    tools:context=".HistoricoServicoM">
Renomear para `FragmentHistoricoServico`.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/HistoricoServicoM.kt
Mudar nome para `HistoricoServicoFragment`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/NovoServicoM.kt
Renomear para `NovoServicoFragment`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/PedidoManutencaoM.kt
Renomear para `PedidoManutencaoFragment`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/ServicosMFragment.kt
Renomear para `ServicosFragment`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/drawable/card_background.xml
Deletar; menu será feito de outra forma

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/drawable/ic_manutencao.png
Deletar; menu será feito de outra forma

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_manutencao_m.xml
Esse arquivo deve ser chamado `fragment_manutencao.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_menu_manutencao_m.xml
Deletar esse arquivo; menu será feito de outra forma

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_novo_servico_m.xml
Renomear para `fragment_novo_servico.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_pedido_manutencao_m.xml
Renomear para `fragment_pedido_manutencao.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/fragment_servicos_m.xml
Renomear para `fragment_servicos.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/lista_historico.xml
Renomear para `item_historico` para seguir convenção.

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/layout/lista_servicos.xml
Renomear para `item_servicos.xml`

2024-12-10 21:23 UTC, radialserial commented on app/src/main/res/values/strings.xml
> -    <string name="telefone">Telefone</string>
Essas duas linhas não devem ser deletadas.

2024-12-11 17:34 UTC, radialserial commented on app/src/main/AndroidManifest.xml
> +
Fragmentos não devem ser declarados no manifesto, favor deletar

2024-12-11 17:34 UTC, radialserial commented on app/src/main/java/com/hinade/fleetfix/ManutencaoFragment.kt
Esse arquivo não tem um `fragment_manutencao.xml` correspondente. Por que?

2024-12-11 17:34 UTC, radialserial commented on app/src/main/res/navigation/navigation.xml
> +    app:startDestination="@id/adicionarMulta">
Desfaça essa mudança, por favor. Isso vai fazer com que o aplicativo inicie na tela de multas ao invés da de login.

2024-12-11 17:34 UTC, radialserial commented on app/src/main/res/navigation/navigation.xml
> -            app:popExitAnim="@anim/nav_default_pop_exit_anim" />
Também desfaça essa deleção.

2024-12-11 17:34 UTC, radialserial commented on app/src/main/res/navigation/navigation.xml
> -            app:popExitAnim="@anim/nav_default_pop_exit_anim" />
Também desfaça essa deleção.

2024-12-11 17:37 UTC, radialserial requested changes

2024-12-11 17:37 UTC, radialserial commented on app/src/main/res/layout/fragment_menu_manutencao_m.xml
Esse arquivo deve ser deletado.

2024-12-11 21:45 UTC, closed without merging